/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hellw_ffmpegh264_H264Encoder */
#include <android/log.h>
#define TAG "hellw"
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)


#define FPS 30
#ifndef _Included_com_hellw_ffmpegh264_H264Encoder
#define _Included_com_hellw_ffmpegh264_H264Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hellw_ffmpegh264_H264Encoder
 * Method:    init
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_hellw_ffmpegh264_H264Encoder_init
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_hellw_ffmpegh264_H264Encoder
 * Method:    encoder
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_hellw_ffmpegh264_H264Encoder_encoder
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_hellw_ffmpegh264_H264Encoder
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hellw_ffmpegh264_H264Encoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
