/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#include <android/log.h>
#define TAG "hellw"
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)

/*
 * Class:     com_hellw_ffmpegh264_MainActivity
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_hellw_ffmpegh264_MainActivity_init
  (JNIEnv *, jobject);


